env:
  browser: true
  node: true
  jest: true

parser: babel-eslint

extends:
  - airbnb
  - "plugin:jest/recommended"

settings:
  import/resolver:
    - node
    - webpack

rules:
  import/extensions: 0
  react/prop-types: 0
  react/static-property-placement: 0
  react/prefer-stateless-function: 0
  no-underscore-dangle: 0
  no-param-reassign: 0
  no-console: 0
